version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    volumes:
      - "D:/Volumes/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=sagarmatha
      - MYSQL_USER=sandesh
      - MYSQL_PASSWORD=sagarmatha
      - MYSQL_DATABASE=overall
    ports:
      - "3306:3306"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092 #change localhost to docker container name
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  prometheus:
#    image: prom/prometheus:v2.38.0
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    volumes:
      - "./src/main/resources/monitoring/prometheus:/etc/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  grafana:
#    image: grafana/grafana:9.1.0
    image: grafana/grafana:10.0.10
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - "./src/main/resources/monitoring/grafana/provisioning:/etc/grafana/provisioning/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
